export const CONST = {
    SUBMIT: "SUBMIT_REQUEST",
    SUBMIT_RESET: "SUBMIT_RESET",
    GET_WEATHER_INIT: "GET_WEATHER_INIT",
    GET_WEATHER_SUCESS: "GET_WEATHER_SUCESS",
    GET_WEATHER_ERROR: "GET_WEATHER_ERROR",
    SET_ACTIVE_CITY: "SET_ACTIVE_CITY",
    SET_TEMPREATURE: "SET_TEMPREATURE",
};


